list: $/cwtuning/bots/models/log/columns.yaml
modelClass: Cwtuning\Bots\Models\Log
title: BotsLog
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 50
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'cwtuning/bots/botslog/update/:id'
