list: $/cwtuning/bots/models/youtubercomments/columns.yaml
modelClass: Cwtuning\Bots\Models\YouTuberComments
title: BotsYouTuberComments
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 70
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'cwtuning/bots/botsyoutubercomments/update/:id'
