list: $/cwtuning/bots/models/youtuberplaylists/columns.yaml
modelClass: Cwtuning\Bots\Models\YouTuberPlaylists
title: BotsYouTuberPlayLists
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'cwtuning/bots/botsyoutuberplaylists/update/:id'
