list: $/cwtuning/bots/models/youtubervideos/columns.yaml
modelClass: Cwtuning\Bots\Models\YouTuberVideos
title: BotsYouTuberVideos
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 70
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'cwtuning/bots/botsyoutubervideos/update/:id'
