list: $/cwtuning/bots/models/bot/columns.yaml
modelClass: Cwtuning\Bots\Models\Bot
title: Bots
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'cwtuning/bots/bots/update/:id'
