list: $/cwtuning/bots/models/blogtitlefilter/columns.yaml
modelClass: Cwtuning\Bots\Models\BlogTitleFilter
title: BlogTitleFilter
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'cwtuning/bots/blogtitlefilter/update/:id'
