list: $/cwtuning/bots/models/youtubervideostitlefilter/columns.yaml
modelClass: Cwtuning\Bots\Models\YouTuberVideosTitleFilter
title: BotsYouTuberVideosTitleFilter
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'cwtuning/bots/botsyoutubervideostitlefilter/update/:id'
