list: $/cwtuning/bots/models/youtuberchannels/columns.yaml
modelClass: Cwtuning\Bots\Models\YouTuberChannels
title: BotsYouTuberChannels
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 70
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'cwtuning/bots/botsyoutuberchannels/update/:id'
